sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
env:
    global:
     - TRAVIS=true
install:
  - npm install --build-from-source
  - npm run-script package
  - ls build/stage/${TRAVIS_REPO_SLUG}/releases/download/${TRAVIS_TAG}/*.tar.gz
